/* Main */
export const CHANGE_ADMIN_STATUS = 'CHANGE_ADMIN_STATUS';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
/* Home Page */
export const CHANGE_PAGE_DATA = 'CHANGE_PAGE_DATA';
export const GET_DATA_POSTS = 'GET_DATA_POSTS';

export const CHANGE_NAV_BAR_DATA = 'CHANGE_NAV_BAR_DATA';
export const CHANGE_NAV_BAR_SETTINGS = 'CHANGE_NAV_BAR_SETTINGS';
export const CHANGE_CURRENT_SETTINGS = 'CHANGE_CURRENT_SETTINGS';
export const CHANGE_EVENTS_STATE = 'CHANGE_EVENTS_STATE';
export const CHANGE_CONTACT_US_STATE = 'CHANGE_CONTACT_US_STATE';
export const ADD_CONTACT_DATA = 'ADD_CONTACT_DATA';
export const ADD_UPDATE_NETWORKS_LINKS = 'ADD_UPDATE_NETWORKS_LINKS';
export const ADD_UPDATE_SLIDER_IMAGE = 'ADD_UPDATE_SLIDER_IMAGE';

